### PR TITLE
Added Graduate Admission Classifcation using Adaboost.

### PR DESCRIPTION
**Pull request by Davidportlouis**
- [x]  C++ notebook 
- [x]  Python notebook 
- [x]  Visualization and graphs
- [x]  Markdown annotations & explanations (WIP)
- [x]  Dataset source

### CODE REVIEW

**Comment by Davidportlouis** [comment]
Dataset Source: https://drive.google.com/file/d/1lmV2rTyD8WxgNKanMGlG73swVDO95ued/view?usp=sharing

**Comment by zoq** [comment]
Dataset uploaded - http://datasets.mlpack.org/Admission_Predict.csv

**Review by zoq — COMMENTED** [review]
Looks great to me, let me know if you need any help with the merge conflict.

**Comment by Davidportlouis** [comment]
> Looks great to me, let me know if you need any help with the merge conflict.


Hi @zoq  I'm sorry the uploaded dataset has some issues. Please upload this https://drive.google.com/file/d/18N_ragpP72_Q8FthWtWiRJqMzkxopT0O/view?usp=sharing

**Comment by zoq** [comment]
> > Looks great to me, let me know if you need any help with the merge conflict.
> 
> Hi @zoq I'm sorry the uploaded dataset has some issues. Please upload this https://drive.google.com/file/d/18N_ragpP72_Q8FthWtWiRJqMzkxopT0O/view?usp=sharing

No problem, uploaded the updated dataset.

**Review by zoq — APPROVED** [review]
Looks good to me as well, thanks.

**Pull request merged**
