### PR TITLE
Added Standard GAN for MNIST

### PR DESCRIPTION
**Pull request by hello-fri-end**
Generating hand-written digits using MNIST dataset is the "hello world" program of GANs. Hopefully, this will help new users to get an idea about GAN implementations in mlpack.

### CODE REVIEW

**Comment by kartikdutt18** [comment]
Hey, can you also add notebook for this example as done for other examples. Thanks.

**Comment by hello-fri-end** [comment]
> Hey, can you also add notebook for this example as done for other examples. Thanks.

Sure. I'll do that.

**Comment by hello-fri-end** [comment]
Hey @kartikdutt18 ! I tried to run mlpack/examples on binder but I'm getting the following error: 


_CMake Error at CMakeLists.txt:66 (find_package):
  Could not find a configuration file for package "xtl" that is compatible
  with requested version "0.7.0".

  The following configuration files were considered but not accepted:

    /srv/conda/envs/notebook/lib/cmake/xtl/xtlConfig.cmake, version: 0.6.21



-- Configuring incomplete, errors occurred!
See also "/home/jovyan/xwidgets/build/CMakeFiles/CMakeOutput.log".
Removing intermediate container 44c7bc42f809
The command '/bin/sh -c ./binder/postBuild' returned a non-zero code: 1_

I'm  not sure what this means.

**Comment by shrit** [comment]
@hello-fri-end Are you sure you need `binder` for this example?

**Pull request closed without merging**
