### PR TITLE
Bump to latest versions

### PR DESCRIPTION
**Pull request by dnabanita7**

### CODE REVIEW

**Comment by rcurtin** [comment]
What does this solve and why should we merge it?  There's no description here, so I don't understand what the PR is for.  (If there was already discussion somewhere else and I just don't have context, oops, sorry about that.)

**Comment by zoq** [comment]
Probably a good idea to keep the packages updated, did you test all notebooks, to make sure they are still working?

**Comment by dnabanita7** [comment]
Yes, my bad! Sorry for not describing it properly. The previous versions of matplotlib and soem other packages are not suitable for the python version so had to upgrade it.

**Comment by rcurtin** [comment]
Why are they not suitable?

**Comment by dnabanita7** [comment]
Matplotlib3.1 doesn't support py 3.7 anymore.

**Review by zoq — DISMISSED** [review]
Thanks for looking into this.

**Comment by zoq** [comment]
Hm, looks like we run into another package version issue.

**Comment by dnabanita7** [comment]
I will check this again

**Comment by zoq** [comment]
Thanks, what I did was just opened the binder link from the second post, it worked before, but looks like since then there was another package update.

**Comment by dnabanita7** [comment]
works fine now!

**Review by zoq — APPROVED** [review]
Checked, builds and works, thanks for the updates.

**Comment by zoq** [comment]
Thanks for the update.

**Pull request merged**
