### PR TITLE
Added Gan application

### PR DESCRIPTION
**Pull request by Soonmok**
Added Gan application for mnist dataset

### CODE REVIEW

**Comment by zoq** [comment]
Does this build on your local machine?

**Comment by Soonmok** [comment]
yes. it was.... I will check it again.

**Comment by zoq** [comment]
Okay, let me know if I should take a closer look into the issue, if that worked on your machine.

**Comment by Soonmok** [comment]
Yuppy~! Succeed to build it. Plz review my code ..

**Comment by zoq** [comment]
Not sure, but do you have the results as well?

**Comment by Soonmok** [comment]
Sorry. I made on mistake on path. I will fix it!

**Pull request closed without merging**
