### PR TITLE
Minor Syntax Error

### PR DESCRIPTION
**Pull request by AdarshSantoria**

### CODE REVIEW

**Review by rcurtin — COMMENTED** [review]
Thanks for the fix!  I believe that the only layer that still needs to be adapted for this example to work is the `PReLU` layer, which is being handled in mlpack/mlpack#3420.  Once that's merged, do you want to uncomment the code that skips the `mnist_cnn` build in `.ci/linux-steps.yaml` and `.ci/macos-steps.yaml` and see if the example builds and runs correctly?

**Comment by AdarshSantoria** [comment]
keep open

**Comment by rcurtin** [comment]
Sorry that mlpack-bot got to this one before I did. :)  Let's see if it builds, and if it's green, then I think we can merge it.  Thanks for working on this! :+1:

**Comment by AdarshSantoria** [comment]
Hey @rcurtin, I am getting this in binder
```
bash: line 1:     9 Killed                  ${MAMBA_EXE} env update -p ${NB_PYTHON_PREFIX} --file "binder/environment.yml"
time: 1009.813
```
Can you please help or just provide me some paths to solve this.

**Comment by rcurtin** [comment]
Oops, sorry, this one fell off the list.  Let me try restarting all the checks and let's see what happens, and we can go from there.  Definitely it would be great to merge this fix and get these examples working again.

**Review by rcurtin — APPROVED** [review]
@AdarshSantoria I'm not sure what the error you were encountering was (looks like notebook worker out of RAM?), but after I re-enabled the `mnist_batch_norm` build in its `Makefile`, everything works in the example, so I think this is good to merge. :+1:  Thanks for the fix!

**Comment by AdarshSantoria** [comment]
Thanks for the help.

**Review by zoq — APPROVED** [review]
Looks good to me.

**Comment by AdarshSantoria** [comment]
Keep open

**Comment by rcurtin** [comment]
Oops, forgot to actually hit the merge button...

**Pull request merged**
