### PR TITLE
Test the travis build...

### PR DESCRIPTION
**Pull request by rcurtin**
Don't merge this---I just want to make sure the transition from travis-ci.org to travis-ci.com was successful.

### CODE REVIEW

**Comment by zoq** [comment]
I had the same problem with ensmallen, I thought maybe just transition to azure. I can set this up.

**Comment by rcurtin** [comment]
Yeah, I am looking through their pricing model and it is a nightmare.  I think I have us set up with a "free" 10k credit plan, but presumably it will run out soon enough.  If you want to transition to Azure---or Jenkins---that would be a way better solution.

**Comment by zoq** [comment]
Yeah, Jenkins would probably be even easier to set up.

**Comment by rcurtin** [comment]
Ok, that at least triggered.  Apparently 10k credits is roughly 1000 minutes of build time... since each build takes roughly half an hour, that gives us... just a couple more than 30 builds before we're out.  Sigh...

I think Jenkins might be the better way to go here, but we should keep the build script in this repository instead of in the Jenkins config, and the Jenkins job can just run that script.

**Comment by zoq** [comment]
Agreed, we wanted to set up testing for the notebooks as well, so that would fit perfectly.

**Comment by rcurtin** [comment]
Hmm, I guess we could do the builds in a docker container too to save the extra setup time of installing mlpack's dependencies.  (I guess we still have to build and install mlpack though.)

**Comment by zoq** [comment]
If we do this inside a docker conda env we could install the nightly ensmallen/mlpack conda package, instead of building mlpack each time.

**Comment by rcurtin** [comment]
That works too---do you want to set that up?  If not I'll put it on my list (could be a few days).  Anyway at least this is working so I'll close this PR. :+1:

**Pull request closed without merging**
