### PR TITLE
Adapt neural network examples to ann-vtable branch

### PR DESCRIPTION
**Pull request by rcurtin**
In this PR I've gone through the various examples and adapted them to the changes in https://github.com/mlpack/mlpack/pull/2777.  Of course it will fail to build right now, but once #2777 is merged, it should work.

There are a few examples (`mnist_vae_cnn`, `mnist_batch_norm`, and the reinforcement learning examples) that I cannot currently adapt, since there are some layers or other functionality that is not yet supported in #2777.

I also did some small cleanups here and there.

### CODE REVIEW

**Comment by zoq** [comment]
With https://github.com/mlpack/mlpack/pull/2777 merged, let's restart the CI jobs and see if they run through.

**Comment by shrit** [comment]
It seems as if there was an indentation issue, which make it really hard to see the changes and to review this PR

**Comment by rcurtin** [comment]
Yeah, the style was wrong in a couple of files so I fixed that too.  Sorry if it makes the diff hard. :(

**Review by zoq — APPROVED** [review]
Looks good to me, no comments from my side.

**Review by kartikdutt18 — APPROVED** [review]
LGTM!

**Pull request merged**
