### PR TITLE
Added MicroChip QA classification using Naive Bayes Classifier

### PR DESCRIPTION
**Pull request by Davidportlouis**
- [x]  C++ notebook 
- [x]  Python notebook 
- [x]  Visualization and graphs
- [x]  Markdown annotations & explanations (WIP)
- [x]  Dataset source 

Dataset source: https://drive.google.com/file/d/177A_g2tr_0_h0aicE-ZFgU5hy0PzTg-Y/view?usp=sharing

### CODE REVIEW

**Comment by bkmgit** [comment]
Nice overview. Maybe helpful to use cross validation since it is a relatively small dataset https://www.mlpack.org/doc/mlpack-3.1.1/doxygen/cv.html

**Comment by bkmgit** [comment]
Typo: hatemap -> heatmap

**Comment by bkmgit** [comment]
an heatmap -> a heatmap
an ROC -> a ROC

**Comment by bkmgit** [comment]
May also want to try [DBSCAN](https://www.mlpack.org/doc/stable/python_documentation.html#dbscan) for clustering this dataset.

**Review by zoq — COMMENTED** [review]
Dataset uploaded - http://datasets.mlpack.org/microChip.csv

**Review by zoq — APPROVED** [review]
Looks great to me.

**Comment by zoq** [comment]
> May also want to try [DBSCAN](https://www.mlpack.org/doc/stable/python_documentation.html#dbscan) for clustering this dataset.

We discussed this in our meeting, and we concluded that we will merge it for now and either create a new notebook or extend it in another PR afterwards.

**Review by kartikdutt18 — APPROVED** [review]
Looks Good to me as well. Thanks for putting this together!

**Pull request merged**
