### PR TITLE
Attempt to run examples on Travis.

### PR DESCRIPTION
**Pull request by rcurtin**
I'm not yet sure how to run any of the notebook examples as part of the build, but let's see if this script works for the C++ examples.

### CODE REVIEW

**Comment by zoq** [comment]
> I'm not yet sure how to run any of the notebook examples as part of the build, but let's see if this script works for the C++ examples.

I can handle the notebook part.

**Comment by rcurtin** [comment]
Ok, I think this one is ready!  There are four examples that don't work right, but I'll open issues for each of these and we can fix them one by one.  I think that in many cases the fixes should be pretty straightforward. :+1:

**Review by birm — APPROVED** [review]
Yey Testing!

**Review by zoq — APPROVED** [review]
Thanks for putting this together.

**Comment by rcurtin** [comment]
Awesome; hopefully this will be helpful for others adding new examples. :+1:

**Pull request merged**
