### PR TITLE
Update the example with best coordinates callback

### PR DESCRIPTION
**Pull request by shrit**
Signed-off-by: Omar Shrit <omar@shrit.me>

### CODE REVIEW

**Review by rcurtin — APPROVED** [review]
Ahh, nice catch, we should definitely use this too.

**Comment by rcurtin** [comment]
Also, should we also apply the same changes to the other examples?

**Comment by shrit** [comment]
Yes, I will update other examples too.

**Comment by rcurtin** [comment]
Thanks @shrit! :+1:

**Pull request merged**
