### PR TITLE
Install SoS kernel

### PR DESCRIPTION
**Pull request by zoq**
The package allows us to run different kernel in the same notebook, and also exchange data between different kernel. For example we can do run mlpack's logistic regression method with the C++ kernel, and plot the data with Python or create an interactive plot in JavaScript.

For some more details see https://vatlab.github.io/sos-docs/

### CODE REVIEW

**Review by coatless — APPROVED** [review]

**Comment by jonpsy** [comment]
Question: will this render all our utils along with matplotlib-cpp useless?

**Comment by coatless** [comment]
Not at all. This just provides convenience for folks who are used to using Python visualization libraries. 

`matplotlib-cpp` shines because it handles the glue without needing a specialized kernel (SoS, in this case).

**Review by kartikdutt18 — APPROVED** [review]
LGTM!

**Comment by jonpsy** [comment]
As the wise saying goes:

"LESGO!!"
           ~DaBaby.

**Pull request merged**
